### ISSUE TITLE
DB neuer Port

### ISSUE THREAD

**Issue by xp24** [FriendsOfShopware/FroshPlatformAdminer#14]
### Question

Moin Leute, wir haben in einem SW6 Projekt die Maria DB Version durch neue DB und Dump geändert, dadurch hat sich auch der Port verändert. In der .env steht natürlich alles passend drin und der Shop funktioniert auch wie er soll. Nur das Plugin kann keine Verbindung  zur DB herstellen, es versucht immer noch die alte DB zu öffnen?!

Ich habe versucht den Port bei der Anmeldung gleich mitzugeben 127.0.0.1:14502 - hat nicht funktioniert.

**Comment by tinect** [comment]
Hey,

Is the problem still existent? Do you get any errors? Which plugin version do you use?

There was a fix in 0.3.4 for reading the database credentials.

Best Regards,
Sebastian

**Comment by xp24** [comment]
Moin Sebastian,

Danke für die Rückmeldung.

Jepp, das Problem ist noch immer da, aber ich habe das Update auch noch nicht eingespielt


Mit besten Grüßen
Marco Thrum



xp24 - Screen-, Print-, Fotodesign
Shopware 5/6 Development - eCommerce

Montag-Donnerstag:
8:00-12:00 Uhr
13:30-16:30 Uhr
Freitag:
per Mail erreichbar

Festnetz: +49 (0)38328-652020
Mobil: +49 (0)173-6571433

www.xp24.biz
***@***.***
facebook.com/xp24.biz/
https://www.xing.com/profile/Marco_Thrum/cv
https://www.freelancermap.de/freelancer-verzeichnis/profile/entwicklung/44373-profil-marco-thrum-xp24-shopware-freelancer-5-6-frontend-entwickler-sw5-6-betreuung.html
Am 28. Feb. 2023, 08:58 +0100 schrieb tinect ***@***.***>:

**Comment by tinect** [comment]
We'll close here due to interactivity.
