### ISSUE TITLE
No open button

### ISSUE THREAD

**Issue by Teddielike** [FriendsOfShopware/FroshPlatformAdminer#18]
### PHP Version

8.2

### Shopware Version

>= 6.5

### Actual behaviour

No button was created to open in the administration.

### Expected behaviour

Button to open Adminer

### Steps to Reproduce?

Install in Shopware >= 6.5

**Comment by tinect** [comment]
How did you install the plugin? Did you clone the repo and forgot to build the assets?

![image](https://github.com/FriendsOfShopware/FroshPlatformAdminer/assets/135993/23c14763-1b6f-4ca7-b7ab-323a4008c827)

**Comment by tinect** [comment]
Closed due to inactivity.
