### ISSUE TITLE
/bundles/froshplatformadminer/Adminer/Adminer.php  is accessible to non-authenticated users.

### ISSUE THREAD

**Issue by timruether** [FriendsOfShopware/FroshPlatformAdminer#2]
As adminer is a continuous standard vector for attacks. Please add a check if Shopware backend session user is active.

/bundles/froshplatformadminer/Adminer/Adminer.php  is accessible to non-authenticated users.

Chers

Tim

**Comment by hlohaus** [comment]
see #5
