### ISSUE TITLE
Warning: Trying to access array offset on null in...

### ISSUE THREAD

**Issue by Wachert** [FriendsOfShopware/FroshPlatformAdminer#26]
### PHP Version

8.3.7

### Shopware Version

6.6.3.0

### Plugin Version

2.0.0

### Actual behaviour

Many "Warning: Trying to access array offset on null in" Errors when accessing tables
![image](https://github.com/FriendsOfShopware/FroshPlatformAdminer/assets/16701558/f9771406-560f-4f5c-99b5-27e1c940b099)

Full Message: Warning: Trying to access array offset on null in /var/www/html/custom/plugins/FroshPlatformAdminer/src/Adminer/Adminer.php on line 592

### Expected behaviour

No Errors :D

### Steps to Reproduce?

Install the plugin, open adminer, access a table like products

**Comment by tinect** [comment]
Thank you for opening the issue.
Just to be safe: Warnings are no errors.

But sure, these messages should not be printed.
I'll check the update of the used library.
